name: myPypelineHomeWork_7
on:
  push:
    branches:
    - main
    - release/* 

jobs:
  dependencies:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          cache: 'yarn'
      - name: dependencies install
        run: yarn ci

  build:
    needs: [dependencies]
    runs-on: ubuntu-24.04
    steps:
      - name: dependencies install
        run: yarn ci
      - name: build
        run: yarn build

  linters:
    needs: [dependencies]
    runs-on: ubuntu-24.04
    steps:
      - name: dependencies install
        run: yarn ci
      - name: linting
        run: yarn linters

  deploy:
    needs: [dependencies, build]
    runs-on: ubuntu-24.04
    steps:
      - name: deploy
        run: yarn deploy
